import {
    Goblin,
    Dotter, Vertibat, Moonsect, Lunny, MeatSoldier, Skulnap, Abyssaw, GlidoSpike, Geargle,
    DuskPlant, Silknoir, Skelly, WalterTheGhost, Ben, Gloomlet, Dolly,
    Razorfin, SkeletonFish, SpearFish, JetFish, Piper, Jellion, Voltzeel, Garry,
    Sluggie, BigGreener, Chiquita, Fofinha, LilHornet, KarateCroco, Bramble, Jerry, Vinelash,
    Snailey, Citrifly, Berrifly, LazyMosquito, LeafSlug, Sunflora, Eggry, AngryBee, Bee, Strawspider,
    Toxhop, Venflora, Virefly, Larvox, Venarach, Mycora, Toxwing, Venoblitz, Woxin,
    Cactrix, Blazice, Magmapod, Volcanurtle, VolcanoWasp, Scorvex, EmberFly, Bloburn, Scorble, Lavaryn,
    IceSilknoir, CrystalWasp, IcePlant, Globby, Cryopede, DrillIce, Frostling, Frobat,
    Wardrake, Sigilfly, Mawrune, Golex, Voidserp, Oozel, Runecko, Runespider, Sigilash,
    Plazer, Veynoculus, Crabula, Johnny, Spindle, Borion, Vespion, Nebulure, Oculith, Lancer, Astraider, Frogula,
} from "../entities/enemies/enemies.js";

export function getEnemySpawnConfig(game) {
    const isRaining = game.background?.isRaining;

    return {
        Map1: [
            { type: Goblin,      probability: 0.05, spawningDistance: 0 },
            { type: Dotter,      probability: 0.35, spawningDistance: 0 },
            { type: Moonsect,    probability: 0.3,  spawningDistance: 0 },
            { type: Geargle,     probability: 0.2,  spawningDistance: 0 },
            { type: Lunny,       probability: 0.3,  spawningDistance: 0 },
            { type: MeatSoldier, probability: 0.1,  spawningDistance: 0 },
            { type: Skulnap,     probability: 0.25, spawningDistance: 50 },
            { type: Abyssaw,     probability: 0.06, spawningDistance: 100 },
            { type: GlidoSpike,  probability: 0.1,  spawningDistance: 150 },
        ],
        Map2: [
            { type: Goblin,        probability: 0.05, spawningDistance: 0 },
            { type: Vertibat,      probability: 0.1,  spawningDistance: 0 },
            { type: DuskPlant,     probability: 0.2,  spawningDistance: 0 },
            { type: Silknoir,      probability: 0.4,  spawningDistance: 0 },
            { type: WalterTheGhost,probability: 0.2,  spawningDistance: 0 },
            { type: Ben,           probability: 0.09, spawningDistance: 0 },
            { type: Skelly,        probability: 0.07, spawningDistance: 50 },
            { type: Gloomlet,      probability: 0.08, spawningDistance: 50 },
            { type: Dolly,         probability: 0.01, spawningDistance: 100 },
        ],
        Map3: [
            { type: Goblin,      probability: 0.05, spawningDistance: 0 },
            { type: Razorfin,    probability: 0.2,  spawningDistance: 0 },
            { type: SkeletonFish,probability: 0.2,  spawningDistance: 0 },
            { type: SpearFish,   probability: 0.1,  spawningDistance: 0 },
            { type: JetFish,     probability: 0.05, spawningDistance: 0 },
            { type: Piper,       probability: 0.2,  spawningDistance: 50 },
            { type: Jellion,     probability: 0.09, spawningDistance: 70 },
            { type: Voltzeel,    probability: 0.08, spawningDistance: 100 },
            { type: Garry,       probability: 0.07, spawningDistance: 130 },
        ],
        Map4: [
            { type: Goblin,     probability: 0.05, spawningDistance: 0 },
            { type: BigGreener, probability: 0.2,  spawningDistance: 0 },
            { type: Chiquita,   probability: 0.2,  spawningDistance: 0 },
            { type: Fofinha,    probability: 0.2,  spawningDistance: 0 },
            { type: Sluggie,    probability: 0.3,  spawningDistance: 0 },
            { type: LilHornet,  probability: 0.05, spawningDistance: 0 },
            { type: KarateCroco,probability: 0.05, spawningDistance: 0 },
            { type: Bramble,    probability: 0.01, spawningDistance: 70 },
            { type: Jerry,      probability: 0.05, spawningDistance: 120 },
            { type: Vinelash,   probability: 0.04, spawningDistance: 140 },
        ],
        Map5: [
            { type: Goblin,       probability: 0.05, spawningDistance: 0 },
            { type: Snailey,      probability: 0.05, spawningDistance: 0 },
            { type: Citrifly,     probability: 0.2,  spawningDistance: 0 },
            { type: Berrifly,     probability: 0.2,  spawningDistance: 0 },
            { type: LazyMosquito, probability: 0.2,  spawningDistance: 0 },
            { type: LeafSlug,     probability: 0.15, spawningDistance: 0 },
            { type: Sunflora,     probability: 0.1,  spawningDistance: 0 },
            { type: Eggry,        probability: 0.3,  spawningDistance: 0 },
            { type: isRaining ? AngryBee : Bee, probability: isRaining ? 0.06 : 0.07, spawningDistance: 0 },
            { type: Strawspider,  probability: 0.05, spawningDistance: 0 },
        ],
        Map6: [
            { type: Goblin,    probability: 0.05, spawningDistance: 0 },
            { type: Larvox,    probability: 0.2,  spawningDistance: 0 },
            { type: Venflora,  probability: 0.1,  spawningDistance: 0 },
            { type: Venarach,  probability: 0.2,  spawningDistance: 0 },
            { type: Venoblitz, probability: 0.05, spawningDistance: 0 },
            { type: Virefly,   probability: 0.08, spawningDistance: 0 },
            { type: Toxwing,   probability: 0.09, spawningDistance: 0 },
            { type: Woxin,     probability: 0.07, spawningDistance: 50 },
            { type: Toxhop,    probability: 0.07, spawningDistance: 100 },
            { type: Mycora,    probability: 0.04, spawningDistance: 150 },
        ],
        Map7: [
            { type: Goblin,      probability: 0.05, spawningDistance: 0 },
            { type: EmberFly,    probability: 0.2,  spawningDistance: 0 },
            { type: Scorble,     probability: 0.1,  spawningDistance: 0 },
            { type: Blazice,     probability: 0.07, spawningDistance: 0 },
            { type: Cactrix,     probability: 0.1,  spawningDistance: 0 },
            { type: Volcanurtle, probability: 0.1,  spawningDistance: 0 },
            { type: Bloburn,     probability: 0.08, spawningDistance: 0 },
            { type: VolcanoWasp, probability: 0.04, spawningDistance: 30 },
            { type: Magmapod,    probability: 0.08, spawningDistance: 100 },
            { type: Scorvex,     probability: 0.09, spawningDistance: 100 },
            { type: Lavaryn,     probability: 0.06, spawningDistance: 150 },
        ],
        BonusMap1: [
            { type: Goblin,      probability: 0.05, spawningDistance: 0 },
            { type: IcePlant,    probability: 0.2,  spawningDistance: 0 },
            { type: Cryopede,    probability: 0.2,  spawningDistance: 0 },
            { type: IceSilknoir, probability: 0.1,  spawningDistance: 0 },
            { type: Frostling,   probability: 0.06, spawningDistance: 0 },
            { type: Frobat,      probability: 0.2,  spawningDistance: 0 },
            { type: CrystalWasp, probability: 0.05, spawningDistance: 0 },
            { type: Globby,      probability: 0.07, spawningDistance: 50 },
            { type: DrillIce,    probability: 0.06, spawningDistance: 100 },
        ],
        BonusMap2: [
            { type: Goblin,      probability: 0.05, spawningDistance: 0 },
            { type: Sigilfly,    probability: 0.1,  spawningDistance: 0 },
            { type: Oozel,       probability: 0.15, spawningDistance: 0 },
            { type: Runespider,  probability: 0.1,  spawningDistance: 0 },
            { type: Golex,       probability: 0.07, spawningDistance: 0 },
            { type: Voidserp,    probability: 0.09, spawningDistance: 0 },
            { type: Sigilash,    probability: 0.05, spawningDistance: 0 },
            { type: Mawrune,     probability: 0.06, spawningDistance: 70 },
            { type: Runecko,     probability: 0.05, spawningDistance: 100 },
            { type: Wardrake,    probability: 0.04, spawningDistance: 150 },
        ],
        BonusMap3: [
            { type: Goblin,     probability: 0.05, spawningDistance: 0 },
            { type: Nebulure,   probability: 0.05, spawningDistance: 0 },
            { type: Veynoculus, probability: 0.25, spawningDistance: 0 },
            { type: Spindle,    probability: 0.2,  spawningDistance: 0 },
            { type: Plazer,     probability: 0.1,  spawningDistance: 0 },
            { type: Crabula,    probability: 0.05, spawningDistance: 0 },
            { type: Vespion,    probability: 0.1,  spawningDistance: 0 },
            { type: Johnny,     probability: 0.04, spawningDistance: 0 },
            { type: Lancer,     probability: 0.04, spawningDistance: 0 },
            { type: Oculith,    probability: 0.05, spawningDistance: 50 },
            { type: Frogula,    probability: 0.04, spawningDistance: 100 },
            { type: Astraider,  probability: 0.04, spawningDistance: 100 },
            { type: Borion,     probability: 0.04, spawningDistance: 150 },
        ],
    };
}
